# ⚠ CAUTION ⚠
# Be sure to enclose the information in double quotation marks.

# TWITTER SETTINGS
CONSUMER_KEY = "YOUR CONSUMER KEY HERE" # YOUR API KEY HERE
CONSUMER_SECRET = "YOUR CONSUMER KEY SECRET HERE" # YOUR API SECRET HERE
ACCESS_TOKEN = "YOUR ACCESS TOKEN HERE" # YOUR ACCESS TOKEN HERE
ACCESS_TOKEN_SECRET = "YOUR ACCESS TOKEN SECRET HERE" #YOUR ACCESS TOKEN SECRET HERE

#TWEET MESSAGE TEMPLATE(YOU CAN USE VARIABLES YOUR TWEET MESSAGE. CHECK OUT docs/variables.md)
CHANGE_STATUS_TWEET = "(owner) has changed the status of the Discord to (status)."  # WHEN YOUR STATUS HAS CHANGED
START_ACTIVITY_TWEET = "(owner) has started the activity of Discord to (activity)." # WHEN YOUR ACTIVITY HAS STARTED
END_ACTIVITY_TWEET = "(owner) has ended (activity) of Discord." # WHEN YOUR ACTIVITY ENDED

LANG = 'en' # CHANGE STATUS LANGAGE(AVAILABLE ENGLISH(en)-> ONLINE, JAPANESE(ja)-> オンライン)

# AFTER SETUP THIS FILE, YOU MUST CHANGE THIS FILE NAME 'twitter.py'

# HOW TO WRITE THIS FILE? CHECK OUT docs/how_to_use.md